[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = ['npm install', 'cd backend && npm install']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'node backend/src/server.js'